schema: replace PostgreSQL procedure with FUNCTION
PostgreSQL versions prior to 11 doesn't support SQL procedures, so we
either need to require PostgreSQL version 11 as the minimum supported
version or replace it with a function. This commit does the latter.
Also, it adds the `-v ON_ERROR_STOP=1` argument to the documented `psql`
command for applying our schemas, which causes the psql command to
immediately stop on error, e.g., if the function raises an error like
this:

```
$ psql -v ON_ERROR_STOP=1 -U postgres notifications_test < something.sql
ERROR:  Schema version mismatch: expected v2.0, got v1.0. Please apply all previous upgrade scripts in order before applying this one.
CONTEXT:  PL/pgSQL function assert_correct_schema_version(text) line 10 at RAISE
```